-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closures_mut_args]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace closures_mut_args

/-- Trait declaration: [core::ops::function::FnOnce::<_, (_, &_ mut _), _>]
    Source: '/rustc/library/core/src/ops/function.rs', lines 242:0-242:35
    Name pattern: [core::ops::function::FnOnce]
    Visibility: public -/
@[rust_trait "core::ops::function::FnOnce"]
structure core.ops.function.FnOnce.InstT0PairT1Mut0T2T3 (T0 : Type) (T1 : Type)
  (T2 : Type) (T3 : Type) where
  call_once : T0 → (T1 × T2) → Result (T3 × T2)

/-- Trait declaration: [core::ops::function::FnMut::<_, (_, &_ mut _), _>]
    Source: '/rustc/library/core/src/ops/function.rs', lines 163:0-163:48
    Name pattern: [core::ops::function::FnMut]
    Visibility: public -/
@[rust_trait "core::ops::function::FnMut"
  (parentClauses := ["FnOnceInstT0PairT1Mut0T2T3Inst"])]
structure core.ops.function.FnMut.InstT0PairT1Mut0T2T3 (T0 : Type) (T1 : Type)
  (T2 : Type) (T3 : Type) where
  FnOnceInstT0PairT1Mut0T2T3Inst :
    core.ops.function.FnOnce.InstT0PairT1Mut0T2T3 T0 T1 T2 T3
  call_mut : T0 → (T1 × T2) → Result (T3 × (T0 × T2))

/-- [closures_mut_args::call_mut_arg]:
    Source: 'tests/src/closures_mut_args.rs', lines 4:0-9:1
    Visibility: public -/
def call_mut_arg
  {A : Type} (coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst :
  core.ops.function.FnMut.InstT0PairT1Mut0T2T3 A Std.Usize (alloc.vec.Vec
  Std.U8) Unit) (append : A) (dst : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let (_, (_, dst1)) ←
    coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst.call_mut append (0#usize, dst)
  ok dst1

end closures_mut_args
