-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closures_mut_captures]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace closures_mut_captures

/-- Trait declaration: [core::ops::function::FnOnce::<_, (_, &_ mut _), _>]
    Source: '/rustc/library/core/src/ops/function.rs', lines 242:0-242:35
    Name pattern: [core::ops::function::FnOnce]
    Visibility: public -/
@[rust_trait "core::ops::function::FnOnce"]
structure core.ops.function.FnOnce.InstT0PairT1Mut0T2T3 (T0 : Type) (T1 : Type)
  (T2 : Type) (T3 : Type) where
  call_once : T0 → (T1 × T2) → Result (T3 × T2)

/-- Trait declaration: [core::ops::function::FnMut::<_, (_, &_ mut _), _>]
    Source: '/rustc/library/core/src/ops/function.rs', lines 163:0-163:48
    Name pattern: [core::ops::function::FnMut]
    Visibility: public -/
@[rust_trait "core::ops::function::FnMut"
  (parentClauses := ["FnOnceInstT0PairT1Mut0T2T3Inst"])]
structure core.ops.function.FnMut.InstT0PairT1Mut0T2T3 (T0 : Type) (T1 : Type)
  (T2 : Type) (T3 : Type) where
  FnOnceInstT0PairT1Mut0T2T3Inst :
    core.ops.function.FnOnce.InstT0PairT1Mut0T2T3 T0 T1 T2 T3
  call_mut : T0 → (T1 × T2) → Result (T3 × (T0 × T2))

/-- [closures_mut_captures::call_fn_mut_one::closure]
    Source: 'tests/src/closures_mut_captures.rs', lines 21:20-21:39 -/
@[reducible]
def call_fn_mut_one.closure := Slice Std.U8

/-- [closures_mut_captures::call_fn_mut_one::{impl core::ops::function::FnMut<(usize,), ()> for closures_mut_captures::call_fn_mut_one::closure<'_0>}::call_mut]:
    Source: 'tests/src/closures_mut_captures.rs', lines 21:20-21:39 -/
def call_fn_mut_one.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
  (c : call_fn_mut_one.closure) (tupled_args : Std.Usize) :
  Result (Unit × call_fn_mut_one.closure)
  := do
  let s ← Slice.update c tupled_args 0#u8
  ok ((), s)

/-- [closures_mut_captures::call_fn_mut_one]:
    Source: 'tests/src/closures_mut_captures.rs', lines 20:0-23:1
    Visibility: public -/
def call_fn_mut_one
  (a : Slice Std.U8) (i : Std.Usize) : Result (Slice Std.U8) := do
  let (_, write) ←
    call_fn_mut_one.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
      a i
  let a1 := write
  ok a1

/-- [closures_mut_captures::call_fn_mut_one::{impl core::ops::function::FnOnce<(usize,), ()> for closures_mut_captures::call_fn_mut_one::closure<'_0>}::call_once]:
    Source: 'tests/src/closures_mut_captures.rs', lines 21:20-21:39 -/
def
  call_fn_mut_one.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple.call_once
  (c : call_fn_mut_one.closure) (i : Std.Usize) : Result Unit := do
  let _ ←
    call_fn_mut_one.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
      c i
  ok ()

/-- Trait implementation: [closures_mut_captures::call_fn_mut_one::{impl core::ops::function::FnOnce<(usize,), ()> for closures_mut_captures::call_fn_mut_one::closure<'_0>}]
    Source: 'tests/src/closures_mut_captures.rs', lines 21:20-21:39 -/
@[reducible]
def call_fn_mut_one.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple :
  core.ops.function.FnOnce call_fn_mut_one.closure Std.Usize Unit := {
  call_once :=
    call_fn_mut_one.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple.call_once
}

/-- Trait implementation: [closures_mut_captures::call_fn_mut_one::{impl core::ops::function::FnMut<(usize,), ()> for closures_mut_captures::call_fn_mut_one::closure<'_0>}]
    Source: 'tests/src/closures_mut_captures.rs', lines 21:20-21:39 -/
@[reducible]
def call_fn_mut_one.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple :
  core.ops.function.FnMut call_fn_mut_one.closure Std.Usize Unit := {
  FnOnceInst :=
    call_fn_mut_one.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple
  call_mut :=
    call_fn_mut_one.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
}

/-- [closures_mut_captures::call_fn_mut_two::closure]
    Source: 'tests/src/closures_mut_captures.rs', lines 27:20-30:5 -/
def call_fn_mut_two.closure := Slice Std.U8 × Slice Std.U8

/-- [closures_mut_captures::call_fn_mut_two::{impl core::ops::function::FnMut<(usize,), ()> for closures_mut_captures::call_fn_mut_two::closure<'_0, '_1>}::call_mut]:
    Source: 'tests/src/closures_mut_captures.rs', lines 27:20-30:5 -/
def call_fn_mut_two.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
  (c : call_fn_mut_two.closure) (tupled_args : Std.Usize) :
  Result (Unit × call_fn_mut_two.closure)
  := do
  let (s, s1) := c
  let s2 ← Slice.update s tupled_args 0#u8
  let s3 ← Slice.update s1 tupled_args 1#u8
  ok ((), (s2, s3))

/-- [closures_mut_captures::call_fn_mut_two]:
    Source: 'tests/src/closures_mut_captures.rs', lines 26:0-32:1
    Visibility: public -/
def call_fn_mut_two
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) :
  Result ((Slice Std.U8) × (Slice Std.U8))
  := do
  let (_, write) ←
    call_fn_mut_two.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
      (a, b) i
  let (s, s1) := write
  let (a1, _) := (s, s1)
  let (_, b1) := (s, s1)
  ok (a1, b1)

/-- [closures_mut_captures::call_fn_mut_two::{impl core::ops::function::FnOnce<(usize,), ()> for closures_mut_captures::call_fn_mut_two::closure<'_0, '_1>}::call_once]:
    Source: 'tests/src/closures_mut_captures.rs', lines 27:20-30:5 -/
def
  call_fn_mut_two.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple.call_once
  (c : call_fn_mut_two.closure) (i : Std.Usize) : Result Unit := do
  let _ ←
    call_fn_mut_two.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
      c i
  ok ()

/-- Trait implementation: [closures_mut_captures::call_fn_mut_two::{impl core::ops::function::FnOnce<(usize,), ()> for closures_mut_captures::call_fn_mut_two::closure<'_0, '_1>}]
    Source: 'tests/src/closures_mut_captures.rs', lines 27:20-30:5 -/
@[reducible]
def call_fn_mut_two.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple :
  core.ops.function.FnOnce call_fn_mut_two.closure Std.Usize Unit := {
  call_once :=
    call_fn_mut_two.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple.call_once
}

/-- Trait implementation: [closures_mut_captures::call_fn_mut_two::{impl core::ops::function::FnMut<(usize,), ()> for closures_mut_captures::call_fn_mut_two::closure<'_0, '_1>}]
    Source: 'tests/src/closures_mut_captures.rs', lines 27:20-30:5 -/
@[reducible]
def call_fn_mut_two.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple :
  core.ops.function.FnMut call_fn_mut_two.closure Std.Usize Unit := {
  FnOnceInst :=
    call_fn_mut_two.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple
  call_mut :=
    call_fn_mut_two.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
}

/-- [closures_mut_captures::call_fn_mut_mixed::closure]
    Source: 'tests/src/closures_mut_captures.rs', lines 41:19-44:5 -/
def call_fn_mut_mixed.closure (A : Type) :=
  Slice Std.U8 × A × alloc.vec.Vec Std.U8

/-- [closures_mut_captures::call_fn_mut_mixed::{impl core::ops::function::FnMut<(usize,), ()> for closures_mut_captures::call_fn_mut_mixed::closure<'_0, '_1, '_2, A>}::call_mut]:
    Source: 'tests/src/closures_mut_captures.rs', lines 41:19-44:5 -/
def
  call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
  {A : Type} (coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst :
  core.ops.function.FnMut.InstT0PairT1Mut0T2T3 A Std.U8 (alloc.vec.Vec Std.U8)
  Unit) (c : call_fn_mut_mixed.closure A) (tupled_args : Std.Usize) :
  Result (Unit × (call_fn_mut_mixed.closure A))
  := do
  let (s, t, v) := c
  let s1 ← Slice.update s tupled_args 0#u8
  let i ← Slice.index_usize s1 tupled_args
  let (_, (t1, v1)) ←
    coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst.call_mut t (i, v)
  ok ((), (s1, t1, v1))

/-- [closures_mut_captures::call_fn_mut_mixed]:
    Source: 'tests/src/closures_mut_captures.rs', lines 37:0-46:1
    Visibility: public -/
def call_fn_mut_mixed
  {A : Type} (coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst :
  core.ops.function.FnMut.InstT0PairT1Mut0T2T3 A Std.U8 (alloc.vec.Vec Std.U8)
  Unit) (a : Slice Std.U8) (append : A) (dst : alloc.vec.Vec Std.U8) :
  Result ((Slice Std.U8) × (alloc.vec.Vec Std.U8))
  := do
  let (_, step) ←
    call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
      coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst (a, append, dst) 0#usize
  let (s, t, v) := step
  let (a1, _, _) := (s, t, v)
  let (_, _, dst1) := (s, t, v)
  ok (a1, dst1)

/-- [closures_mut_captures::call_fn_mut_mixed::{impl core::ops::function::FnOnce<(usize,), ()> for closures_mut_captures::call_fn_mut_mixed::closure<'_0, '_1, '_2, A>}::call_once]:
    Source: 'tests/src/closures_mut_captures.rs', lines 41:19-44:5 -/
def
  call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple.call_once
  {A : Type} (coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst :
  core.ops.function.FnMut.InstT0PairT1Mut0T2T3 A Std.U8 (alloc.vec.Vec Std.U8)
  Unit) (c : call_fn_mut_mixed.closure A) (i : Std.Usize) :
  Result Unit
  := do
  let _ ←
    call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
      coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst c i
  ok ()

/-- Trait implementation: [closures_mut_captures::call_fn_mut_mixed::{impl core::ops::function::FnOnce<(usize,), ()> for closures_mut_captures::call_fn_mut_mixed::closure<'_0, '_1, '_2, A>}]
    Source: 'tests/src/closures_mut_captures.rs', lines 41:19-44:5 -/
@[reducible]
def call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple {A :
  Type} (coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst :
  core.ops.function.FnMut.InstT0PairT1Mut0T2T3 A Std.U8 (alloc.vec.Vec Std.U8)
  Unit) : core.ops.function.FnOnce (call_fn_mut_mixed.closure A) Std.Usize Unit
  := {
  call_once :=
    call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple.call_once
    coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst
}

/-- Trait implementation: [closures_mut_captures::call_fn_mut_mixed::{impl core::ops::function::FnMut<(usize,), ()> for closures_mut_captures::call_fn_mut_mixed::closure<'_0, '_1, '_2, A>}]
    Source: 'tests/src/closures_mut_captures.rs', lines 41:19-44:5 -/
@[reducible]
def call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple {A :
  Type} (coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst :
  core.ops.function.FnMut.InstT0PairT1Mut0T2T3 A Std.U8 (alloc.vec.Vec Std.U8)
  Unit) : core.ops.function.FnMut (call_fn_mut_mixed.closure A) Std.Usize Unit
  := {
  FnOnceInst :=
    call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeTuple
    coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst
  call_mut :=
    call_fn_mut_mixed.closure.Insts.CoreOpsFunctionFnMutTupleUsizeTuple.call_mut
    coreopsfunctionFnMutInstT0PairT1Mut0T2T3Inst
}

end closures_mut_captures
