-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ctor_as_fn]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace ctor_as_fn

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1157:4-1159:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- [ctor_as_fn::E]
    Source: 'tests/src/ctor_as_fn.rs', lines 9:0-12:1
    Visibility: public -/
@[discriminant isize]
inductive E where
| A : Std.Usize → E
| B : Std.Usize → E

/-- [ctor_as_fn::E::A]:
    Source: 'tests/src/ctor_as_fn.rs', lines 10:4-10:12 -/
def E.A.ctor (i : Std.Usize) : Result E := do
  ok (E.A i)

/-- [ctor_as_fn::E::B]:
    Source: 'tests/src/ctor_as_fn.rs', lines 11:4-11:12 -/
def E.B.ctor (i : Std.Usize) : Result E := do
  ok (E.B i)

/-- [ctor_as_fn::map_ctor]:
    Source: 'tests/src/ctor_as_fn.rs', lines 15:0-17:1
    Visibility: public -/
def map_ctor (o : Option Std.Usize) : Result (Option E) := do
  core.option.Option.map (BuiltinFnOnce Std.Usize E) o (E.A.ctor)

/-- [ctor_as_fn::map_ctor_b]:
    Source: 'tests/src/ctor_as_fn.rs', lines 20:0-22:1
    Visibility: public -/
def map_ctor_b (o : Option Std.Usize) : Result (Option E) := do
  core.option.Option.map (BuiltinFnOnce Std.Usize E) o (E.B.ctor)

/-- [ctor_as_fn::S]
    Source: 'tests/src/ctor_as_fn.rs', lines 25:0-25:24
    Visibility: public -/
@[reducible]
def S := Std.Usize

/-- [ctor_as_fn::S]:
    Source: 'tests/src/ctor_as_fn.rs', lines 25:0-25:24 -/
def S.ctor (i : Std.Usize) : Result S := do
  ok i

/-- [ctor_as_fn::map_struct_ctor]:
    Source: 'tests/src/ctor_as_fn.rs', lines 27:0-29:1
    Visibility: public -/
def map_struct_ctor (o : Option Std.Usize) : Result (Option S) := do
  core.option.Option.map (BuiltinFnOnce Std.Usize S) o (S.ctor)

end ctor_as_fn
