-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [error_description]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace error_description

/-- [alloc::string::{impl core::fmt::Debug for alloc::string::String}::fmt]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2732:4-2732:60
    Name pattern: [alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt]
    Visibility: public -/
@[rust_fun "alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt"]
axiom alloc.string.String.Insts.CoreFmtDebug.fmt
  :
  String → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [alloc::string::{impl core::fmt::Debug for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 2730:0-2730:26
    Name pattern: [core::fmt::Debug<alloc::string::String>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<alloc::string::String>"]
def alloc.string.String.Insts.CoreFmtDebug : core.fmt.Debug String := {
  fmt := alloc.string.String.Insts.CoreFmtDebug.fmt
}

/-- [alloc::string::{impl core::ops::deref::Deref<str> for alloc::string::String}::deref]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2835:4-2835:27
    Name pattern: [alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref"]
axiom alloc.string.String.Insts.CoreOpsDerefDerefStr.deref
  : String → Result Str

/-- [error_description::MyError]
    Source: 'tests/src/error_description.rs', lines 16:0-18:1
    Visibility: public -/
structure MyError where
  msg : String

/-- [error_description::{impl core::fmt::Debug for error_description::MyError}::fmt]:
    Source: 'tests/src/error_description.rs', lines 15:9-15:14
    Visibility: public -/
def MyError.Insts.CoreFmtDebug.fmt
  (self : MyError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugShared alloc.string.String.Insts.CoreFmtDebug)
      self.msg
  core.fmt.Formatter.debug_struct_field1_finish f (toStr "MyError") (toStr
    "msg") dyn

/-- Trait implementation: [error_description::{impl core::fmt::Debug for error_description::MyError}]
    Source: 'tests/src/error_description.rs', lines 15:9-15:14 -/
@[reducible]
def MyError.Insts.CoreFmtDebug : core.fmt.Debug MyError := {
  fmt := MyError.Insts.CoreFmtDebug.fmt
}

/-- [error_description::{impl core::fmt::Display for error_description::MyError}::fmt]:
    Source: 'tests/src/error_description.rs', lines 21:4-23:5
    Visibility: public -/
def MyError.Insts.CoreFmtDisplay.fmt
  (self : MyError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let s ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref self.msg
  core.fmt.Formatter.write_str f s

/-- Trait implementation: [error_description::{impl core::fmt::Display for error_description::MyError}]
    Source: 'tests/src/error_description.rs', lines 20:0-24:1 -/
@[reducible]
def MyError.Insts.CoreFmtDisplay : core.fmt.Display MyError := {
  fmt := MyError.Insts.CoreFmtDisplay.fmt
}

/-- [error_description::{impl core::error::Error for error_description::MyError}::description]:
    Source: 'tests/src/error_description.rs', lines 27:4-29:5
    Visibility: public -/
def MyError.Insts.CoreErrorError.description
  (self : MyError) : Result Str := do
  alloc.string.String.Insts.CoreOpsDerefDerefStr.deref self.msg

/-- Trait implementation: [error_description::{impl core::error::Error for error_description::MyError}]
    Source: 'tests/src/error_description.rs', lines 26:0-30:1 -/
@[reducible]
def MyError.Insts.CoreErrorError : core.error.Error MyError := {
  fmtDebugInst := MyError.Insts.CoreFmtDebug
  fmtDisplayInst := MyError.Insts.CoreFmtDisplay
  description := MyError.Insts.CoreErrorError.description
}

/-- [error_description::DefaultedError]
    Source: 'tests/src/error_description.rs', lines 35:0-35:26
    Visibility: public -/
@[reducible]
def DefaultedError := Unit

/-- [error_description::{impl core::fmt::Debug for error_description::DefaultedError}::fmt]:
    Source: 'tests/src/error_description.rs', lines 34:9-34:14
    Visibility: public -/
def DefaultedError.Insts.CoreFmtDebug.fmt
  (self : DefaultedError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str f (toStr "DefaultedError")

/-- Trait implementation: [error_description::{impl core::fmt::Debug for error_description::DefaultedError}]
    Source: 'tests/src/error_description.rs', lines 34:9-34:14 -/
@[reducible]
def DefaultedError.Insts.CoreFmtDebug : core.fmt.Debug DefaultedError := {
  fmt := DefaultedError.Insts.CoreFmtDebug.fmt
}

/-- [error_description::{impl core::fmt::Display for error_description::DefaultedError}::fmt]:
    Source: 'tests/src/error_description.rs', lines 38:4-40:5
    Visibility: public -/
def DefaultedError.Insts.CoreFmtDisplay.fmt
  (self : DefaultedError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str f (toStr "defaulted")

/-- Trait implementation: [error_description::{impl core::fmt::Display for error_description::DefaultedError}]
    Source: 'tests/src/error_description.rs', lines 37:0-41:1 -/
@[reducible]
def DefaultedError.Insts.CoreFmtDisplay : core.fmt.Display DefaultedError := {
  fmt := DefaultedError.Insts.CoreFmtDisplay.fmt
}

/-- Trait implementation: [error_description::{impl core::error::Error for error_description::DefaultedError}]
    Source: 'tests/src/error_description.rs', lines 43:0-43:32 -/
@[reducible]
impl_def DefaultedError.Insts.CoreErrorError : core.error.Error DefaultedError
  := {
  fmtDebugInst := DefaultedError.Insts.CoreFmtDebug
  fmtDisplayInst := DefaultedError.Insts.CoreFmtDisplay
  description := core.error.Error.description.default
    DefaultedError.Insts.CoreErrorError
}

end error_description
