-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [fn_def_regions]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace fn_def_regions

/-- [core::iter::adapters::filter::Filter]
    Source: '/rustc/library/core/src/iter/adapters/filter.rs', lines 21:0-21:23
    Name pattern: [core::iter::adapters::filter::Filter]
    Visibility: public -/
@[rust_type "core::iter::adapters::filter::Filter"]
axiom core.iter.adapters.filter.Filter (I : Type) (P : Type) : Type

/-- [core::iter::traits::iterator::Iterator::map]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 831:4-834:34
    Name pattern: [core::iter::traits::iterator::Iterator::map]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::map"]
axiom core.iter.traits.iterator.Iterator.map.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) :
  Self → F → Result (core.iter.adapters.map.Map Self F)

/-- [core::iter::traits::iterator::Iterator::filter]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 952:4-955:38
    Name pattern: [core::iter::traits::iterator::Iterator::filter]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::filter"]
axiom core.iter.traits.iterator.Iterator.filter.default
  {Self : Type} {P : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutPTupleSharedClause0_ItemBoolInst : core.ops.function.FnMut P
  Clause0_Item Bool) :
  Self → P → Result (core.iter.adapters.filter.Filter Self P)

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1157:4-1159:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- [core::option::{core::option::Option<T>}::map_or]:
    Source: '/rustc/library/core/src/option.rs', lines 1221:4-1224:28
    Name pattern: [core::option::{core::option::Option<@T>}::map_or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map_or"]
axiom core.option.Option.map_or
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → U → F → Result U

/-- [fn_def_regions::is_valid_cap_letter]:
    Source: 'tests/src/fn_def_regions.rs', lines 13:0-15:1 -/
def is_valid_cap_letter (b : Std.U8) : Result Bool := do
  if 48#u8 <= b
  then
    if b <= 57#u8
    then ok true
    else
      if 97#u8 <= b
      then
        if b <= 122#u8
        then ok true
        else
          if 65#u8 <= b
          then
            if b <= 90#u8
            then ok true
            else match b with
                 | 95#uscalar => ok true
                 | _ => ok false
          else match b with
               | 95#uscalar => ok true
               | _ => ok false
      else
        if 65#u8 <= b
        then
          if b <= 90#u8
          then ok true
          else match b with
               | 95#uscalar => ok true
               | _ => ok false
        else match b with
             | 95#uscalar => ok true
             | _ => ok false
  else
    if 97#u8 <= b
    then
      if b <= 122#u8
      then ok true
      else
        if 65#u8 <= b
        then
          if b <= 90#u8
          then ok true
          else match b with
               | 95#uscalar => ok true
               | _ => ok false
        else match b with
             | 95#uscalar => ok true
             | _ => ok false
    else
      if 65#u8 <= b
      then
        if b <= 90#u8
        then ok true
        else match b with
             | 95#uscalar => ok true
             | _ => ok false
      else match b with
           | 95#uscalar => ok true
           | _ => ok false

/-- [fn_def_regions::map_or_by_ref]:
    Source: 'tests/src/fn_def_regions.rs', lines 17:0-19:1
    Visibility: public -/
def map_or_by_ref (replacement : Option Std.U8) : Result Bool := do
  core.option.Option.map_or (BuiltinFnOnce Std.U8 Bool) replacement false
    (is_valid_cap_letter)

/-- [fn_def_regions::deref_u8]:
    Source: 'tests/src/fn_def_regions.rs', lines 22:0-24:1 -/
def deref_u8 (b : Std.U8) : Result Std.U8 := do
  ok b

/-- [fn_def_regions::map_by_ref]:
    Source: 'tests/src/fn_def_regions.rs', lines 26:0-28:1
    Visibility: public -/
def map_by_ref
  (s : Slice Std.U8) :
  Result (core.iter.adapters.map.Map (core.slice.iter.Iter Std.U8) (Std.U8 →
    Result Std.U8))
  := do
  let i ← core.slice.Slice.iter s
  core.iter.traits.iterator.Iterator.map.default
    (core.iter.traits.iterator.IteratorSliceIter Std.U8) (BuiltinFnMut Std.U8
    Std.U8) i (deref_u8)

/-- [fn_def_regions::is_nonzero]:
    Source: 'tests/src/fn_def_regions.rs', lines 31:0-33:1 -/
def is_nonzero (b : Std.U8) : Result Bool := do
  ok (b != 0#u8)

/-- [fn_def_regions::filter_by_ref]:
    Source: 'tests/src/fn_def_regions.rs', lines 35:0-37:1
    Visibility: public -/
def filter_by_ref
  (s : Slice Std.U8) :
  Result (core.iter.adapters.filter.Filter (core.slice.iter.Iter Std.U8)
    (Std.U8 → Result Bool))
  := do
  let i ← core.slice.Slice.iter s
  core.iter.traits.iterator.Iterator.filter.default
    (core.iter.traits.iterator.IteratorSliceIter Std.U8) (BuiltinFnMut Std.U8
    Bool) i (is_nonzero)

/-- [fn_def_regions::first]:
    Source: 'tests/src/fn_def_regions.rs', lines 40:0-42:1 -/
def first (s : Slice Std.U8) : Result Std.U8 := do
  Slice.index_usize s 0#usize

/-- [fn_def_regions::map_returns_ref]:
    Source: 'tests/src/fn_def_regions.rs', lines 44:0-46:1
    Visibility: public -/
def map_returns_ref (o : Option (Slice Std.U8)) : Result (Option Std.U8) := do
  core.option.Option.map (BuiltinFnOnce (Slice Std.U8) Std.U8) o (first)

/-- [fn_def_regions::double]:
    Source: 'tests/src/fn_def_regions.rs', lines 50:0-52:1 -/
def double (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_mul x 2#u32)

/-- [fn_def_regions::map_no_ref]:
    Source: 'tests/src/fn_def_regions.rs', lines 54:0-56:1
    Visibility: public -/
def map_no_ref (o : Option Std.U32) : Result (Option Std.U32) := do
  core.option.Option.map (BuiltinFnOnce Std.U32 Std.U32) o (double)

/-- [fn_def_regions::bump]:
    Source: 'tests/src/fn_def_regions.rs', lines 86:0-88:1 -/
def bump (x : Std.U32) : Result Std.U32 := do
  x + 1#u32

/-- [fn_def_regions::apply_mut]:
    Source: 'tests/src/fn_def_regions.rs', lines 90:0-92:1 -/
def apply_mut
  {F : Type} (coreopsfunctionFnFTupleMut0U32TupleInst : core.ops.function.Fn F
  Std.U32 Unit) (x : Std.U32) (f : F) :
  Result Std.U32
  := do
  let (_, x1) ← coreopsfunctionFnFTupleMut0U32TupleInst.call f x
  ok x1

/-- [fn_def_regions::fn_item_through_generic]:
    Source: 'tests/src/fn_def_regions.rs', lines 94:0-96:1
    Visibility: public -/
def fn_item_through_generic (x : Std.U32) : Result Std.U32 := do
  apply_mut (BuiltinFn Std.U32 Unit) x (bump)

/-- [fn_def_regions::is_pos]:
    Source: 'tests/src/fn_def_regions.rs', lines 102:0-104:1 -/
def is_pos (c : Std.U8) : Result Bool := do
  ok (c > 0#u8)

/-- [fn_def_regions::any_of]: loop body 0:
    Source: 'tests/src/fn_def_regions.rs', lines 108:4-110:5 -/
@[rust_loop_body]
def any_of_loop.body
  {F : Type} (coreopsfunctionFnFTupleSharedU8BoolInst : core.ops.function.Fn F
  Std.U8 Bool) (f : F) (iter : core.slice.iter.Iter Std.U8) (acc : Bool) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U8) × Bool) Bool)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done acc)
  | some b =>
    if acc
    then ok (cont (iter1, true))
    else
      let acc1 ← coreopsfunctionFnFTupleSharedU8BoolInst.call f b
      ok (cont (iter1, acc1))

/-- [fn_def_regions::any_of]: loop 0:
    Source: 'tests/src/fn_def_regions.rs', lines 108:4-110:5 -/
@[rust_loop]
def any_of_loop
  {F : Type} (coreopsfunctionFnFTupleSharedU8BoolInst : core.ops.function.Fn F
  Std.U8 Bool) (iter : core.slice.iter.Iter Std.U8) (f : F) (acc : Bool) :
  Result Bool
  := do
  loop
    (fun (iter1, acc1) => any_of_loop.body
      coreopsfunctionFnFTupleSharedU8BoolInst f iter1 acc1)
    (iter, acc)

/-- [fn_def_regions::any_of]:
    Source: 'tests/src/fn_def_regions.rs', lines 106:0-112:1 -/
def any_of
  {F : Type} (coreopsfunctionFnFTupleShared0U8BoolInst : core.ops.function.Fn F
  Std.U8 Bool) (v : Slice Std.U8) (f : F) :
  Result Bool
  := do
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter v
  any_of_loop coreopsfunctionFnFTupleShared0U8BoolInst iter f false

/-- [fn_def_regions::fn_item_with_live_mut]:
    Source: 'tests/src/fn_def_regions.rs', lines 114:0-120:1
    Visibility: public -/
def fn_item_with_live_mut
  (v : Slice Std.U8) (out : Std.U32) : Result (Bool × Std.U32) := do
  let hit ← any_of (BuiltinFn Std.U8 Bool) v (is_pos)
  if hit
  then let out1 ← out + 1#u32
       ok (true, out1)
  else ok (false, out)

/-- [fn_def_regions::pick_shared]:
    Source: 'tests/src/fn_def_regions.rs', lines 142:0-144:1
    Visibility: public -/
def pick_shared
  (x : Std.U32) (_y : Std.U32) :
  Result (Std.U32 × (Std.U32 → (Std.U32 × Std.U32)))
  := do
  let back := fun x1 => (x1, _y)
  ok (x, back)

/-- [fn_def_regions::pick_shared2]:
    Source: 'tests/src/fn_def_regions.rs', lines 146:0-148:1
    Visibility: public -/
def pick_shared2
  (_x : Std.U32) (y : Std.U32) :
  Result (Std.U32 × (Std.U32 → (Std.U32 × Std.U32)))
  := do
  let back := fun y1 => (_x, y1)
  ok (y, back)

/-- [fn_def_regions::write_through_pick]:
    Source: 'tests/src/fn_def_regions.rs', lines 150:0-153:1
    Visibility: public -/
def write_through_pick
  (a : Std.U32) (b : Std.U32) : Result (Std.U32 × Std.U32) := do
  let (r, pick_shared_back) ← pick_shared a b
  let r1 ← r + 1#u32
  ok (pick_shared_back r1)

/-- [fn_def_regions::write_through_pick2]:
    Source: 'tests/src/fn_def_regions.rs', lines 155:0-158:1
    Visibility: public -/
def write_through_pick2
  (a : Std.U32) (b : Std.U32) : Result (Std.U32 × Std.U32) := do
  let (r, pick_shared2_back) ← pick_shared2 a b
  let r1 ← r + 1#u32
  ok (pick_shared2_back r1)

end fn_def_regions
