-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [higher_ranked_fnmut_free_lifetime]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace higher_ranked_fnmut_free_lifetime

/-- [higher_ranked_fnmut_free_lifetime::find_like]:
    Source: 'tests/src/higher_ranked_fnmut_free_lifetime.rs', lines 26:0-31:1
    Visibility: public -/
def find_like
  {T : Type} {P : Type} (coreopsfunctionFnMutPTupleSharedASharedATBoolInst :
  core.ops.function.FnMut P T Bool) (x : T) (pred : P) :
  Result Bool
  := do
  let (b, _) ←
    coreopsfunctionFnMutPTupleSharedASharedATBoolInst.call_mut pred x
  ok b

end higher_ranked_fnmut_free_lifetime
