-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loop_control_flow]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace loop_control_flow

/-- [loop_control_flow::early_return_in_loop]: loop body 0:
    Source: 'tests/src/loop-control-flow.rs', lines 7:4-17:1
    Visibility: public -/
@[rust_loop_body]
def early_return_in_loop_loop.body
  (stop : Std.U32) (i : Std.U32) : Result (ControlFlow Std.U32 Std.U32) := do
  if i = stop
  then let i1 ← i + 10#u32
       ok (done i1)
  else if i = 4#u32
       then ok (done i)
       else let i1 ← i + 1#u32
            ok (cont i1)

/-- [loop_control_flow::early_return_in_loop]: loop 0:
    Source: 'tests/src/loop-control-flow.rs', lines 7:4-17:1
    Visibility: public -/
@[rust_loop]
def early_return_in_loop_loop
  (stop : Std.U32) (i : Std.U32) : Result Std.U32 := do
  loop
    (fun i1 => early_return_in_loop_loop.body stop i1)
    i

/-- [loop_control_flow::early_return_in_loop]:
    Source: 'tests/src/loop-control-flow.rs', lines 5:0-17:1
    Visibility: public -/
@[reducible]
def early_return_in_loop (stop : Std.U32) : Result Std.U32 := do
  early_return_in_loop_loop stop 0#u32

/-- [loop_control_flow::return_from_nested_loop]: loop body 0:
    Source: 'tests/src/loop-control-flow.rs', lines 23:8-28:9
    Visibility: public -/
@[rust_loop_body]
def return_from_nested_loop_loop.body
  (inner : Std.U32) : Result (ControlFlow Std.U32 Std.U32) := do
  if inner = 1#u32
  then ok (done inner)
  else let inner1 ← inner + 1#u32
       ok (cont inner1)

/-- [loop_control_flow::return_from_nested_loop]: loop 0:
    Source: 'tests/src/loop-control-flow.rs', lines 23:8-28:9
    Visibility: public -/
@[rust_loop]
def return_from_nested_loop_loop (inner : Std.U32) : Result Std.U32 := do
  loop
    (fun inner1 => return_from_nested_loop_loop.body inner1)
    inner

/-- [loop_control_flow::return_from_nested_loop]:
    Source: 'tests/src/loop-control-flow.rs', lines 19:0-30:1
    Visibility: public -/
def return_from_nested_loop : Result Std.U32 := do
  let inner ← return_from_nested_loop_loop 0#u32
  0#u32 + inner

/-- [loop_control_flow::return_value_from_loop_with_break]: loop body 0:
    Source: 'tests/src/loop-control-flow.rs', lines 34:4-44:1
    Visibility: public -/
@[rust_loop_body]
def return_value_from_loop_with_break_loop.body
  (stop : Std.U32) (i : Std.U32) : Result (ControlFlow Std.U32 Std.U32) := do
  if i = stop
  then let i1 ← i * 3#u32
       let i2 ← i1 + 1#u32
       ok (done i2)
  else
    if i = 5#u32
    then let i1 ← i + 20#u32
         ok (done i1)
    else let i1 ← i + 1#u32
         ok (cont i1)

/-- [loop_control_flow::return_value_from_loop_with_break]: loop 0:
    Source: 'tests/src/loop-control-flow.rs', lines 34:4-44:1
    Visibility: public -/
@[rust_loop]
def return_value_from_loop_with_break_loop
  (stop : Std.U32) (i : Std.U32) : Result Std.U32 := do
  loop
    (fun i1 => return_value_from_loop_with_break_loop.body stop i1)
    i

/-- [loop_control_flow::return_value_from_loop_with_break]:
    Source: 'tests/src/loop-control-flow.rs', lines 32:0-44:1
    Visibility: public -/
@[reducible]
def return_value_from_loop_with_break (stop : Std.U32) : Result Std.U32 := do
  return_value_from_loop_with_break_loop stop 0#u32

/-- [loop_control_flow::continue_to_outer_loop]: loop body 1:
    Source: 'tests/src/loop-control-flow.rs', lines 1:0-61:5
    Visibility: public -/
@[rust_loop_body]
def continue_to_outer_loop_loop0_loop0.body
  (i : Std.I32) (acc : Std.U32) (j : Std.I32) :
  Result (ControlFlow (Std.U32 × Std.I32) (Std.U32 × Std.I32 × Bool))
  := do
  if j < 3#i32
  then
    let acc1 ← acc + 10#u32
    let j1 ← j + 1#i32
    if j1 = 2#i32
    then let i1 ← i + 1#i32
         ok (done (acc1, i1, true))
    else ok (cont (acc1, j1))
  else ok (done (acc, i, false))

/-- [loop_control_flow::continue_to_outer_loop]: loop 1:
    Source: 'tests/src/loop-control-flow.rs', lines 1:0-61:5
    Visibility: public -/
@[rust_loop]
def continue_to_outer_loop_loop0_loop0
  (acc : Std.U32) (i : Std.I32) (j : Std.I32) :
  Result (Std.U32 × Std.I32 × Bool)
  := do
  loop
    (fun (acc1, j1) => continue_to_outer_loop_loop0_loop0.body i acc1 j1)
    (acc, j)

/-- [loop_control_flow::continue_to_outer_loop]: loop body 0:
    Source: 'tests/src/loop-control-flow.rs', lines 1:0-61:5
    Visibility: public -/
@[rust_loop_body]
def continue_to_outer_loop_loop0.body
  (acc : Std.U32) (i : Std.I32) :
  Result (ControlFlow (Std.U32 × Std.I32) Std.U32)
  := do
  if i < 3#i32
  then
    let (acc1, i1, aeneas_loop_exit) ←
      continue_to_outer_loop_loop0_loop0 acc i 0#i32
    if aeneas_loop_exit
    then ok (cont (acc1, i1))
    else let acc2 ← acc1 + 100#u32
         let i2 ← i1 + 1#i32
         ok (cont (acc2, i2))
  else ok (done acc)

/-- [loop_control_flow::continue_to_outer_loop]: loop 0:
    Source: 'tests/src/loop-control-flow.rs', lines 1:0-61:5
    Visibility: public -/
@[rust_loop]
def continue_to_outer_loop_loop0
  (acc : Std.U32) (i : Std.I32) : Result Std.U32 := do
  loop
    (fun (acc1, i1) => continue_to_outer_loop_loop0.body acc1 i1)
    (acc, i)

/-- [loop_control_flow::continue_to_outer_loop]:
    Source: 'tests/src/loop-control-flow.rs', lines 46:0-63:1
    Visibility: public -/
@[reducible]
def continue_to_outer_loop : Result Std.U32 := do
  continue_to_outer_loop_loop0 0#u32 0#i32

/-- [loop_control_flow::break_to_outer_loop]: loop body 1:
    Source: 'tests/src/loop-control-flow.rs', lines 1:0-78:5
    Visibility: public -/
@[rust_loop_body]
def break_to_outer_loop_loop0_loop0.body
  (i : Std.I32) (acc : Std.U32) (j : Std.I32) :
  Result (ControlFlow (Std.U32 × Std.I32) (Std.U32 × Bool))
  := do
  if j < 4#i32
  then
    if i = 2#i32
    then
      if j = 1#i32
      then ok (done (acc, true))
      else let acc1 ← acc + 1#u32
           let j1 ← j + 1#i32
           ok (cont (acc1, j1))
    else let acc1 ← acc + 1#u32
         let j1 ← j + 1#i32
         ok (cont (acc1, j1))
  else ok (done (acc, false))

/-- [loop_control_flow::break_to_outer_loop]: loop 1:
    Source: 'tests/src/loop-control-flow.rs', lines 1:0-78:5
    Visibility: public -/
@[rust_loop]
def break_to_outer_loop_loop0_loop0
  (acc : Std.U32) (i : Std.I32) (j : Std.I32) : Result (Std.U32 × Bool) := do
  loop
    (fun (acc1, j1) => break_to_outer_loop_loop0_loop0.body i acc1 j1)
    (acc, j)

/-- [loop_control_flow::break_to_outer_loop]: loop body 0:
    Source: 'tests/src/loop-control-flow.rs', lines 1:0-78:5
    Visibility: public -/
@[rust_loop_body]
def break_to_outer_loop_loop0.body
  (acc : Std.U32) (i : Std.I32) :
  Result (ControlFlow (Std.U32 × Std.I32) Std.U32)
  := do
  if i < 4#i32
  then
    let (acc1, aeneas_loop_exit) ←
      break_to_outer_loop_loop0_loop0 acc i 0#i32
    if aeneas_loop_exit
    then ok (done acc1)
    else let i1 ← i + 1#i32
         ok (cont (acc1, i1))
  else ok (done acc)

/-- [loop_control_flow::break_to_outer_loop]: loop 0:
    Source: 'tests/src/loop-control-flow.rs', lines 1:0-78:5
    Visibility: public -/
@[rust_loop]
def break_to_outer_loop_loop0
  (acc : Std.U32) (i : Std.I32) : Result Std.U32 := do
  loop
    (fun (acc1, i1) => break_to_outer_loop_loop0.body acc1 i1)
    (acc, i)

/-- [loop_control_flow::break_to_outer_loop]:
    Source: 'tests/src/loop-control-flow.rs', lines 65:0-80:1
    Visibility: public -/
@[reducible]
def break_to_outer_loop : Result Std.U32 := do
  break_to_outer_loop_loop0 0#u32 0#i32

/-- [loop_control_flow::test_early_return_in_loop_hit]:
    Source: 'tests/src/loop-control-flow.rs', lines 83:0-85:1 -/
def test_early_return_in_loop_hit : Result Unit := do
  let i ← early_return_in_loop 2#u32
  massert (i = 12#u32)

/- Unit test for [loop_control_flow::test_early_return_in_loop_hit] -/
#assert (test_early_return_in_loop_hit == ok ())

/-- [loop_control_flow::test_early_return_in_loop_break]:
    Source: 'tests/src/loop-control-flow.rs', lines 88:0-90:1 -/
def test_early_return_in_loop_break : Result Unit := do
  let i ← early_return_in_loop 8#u32
  massert (i = 4#u32)

/- Unit test for [loop_control_flow::test_early_return_in_loop_break] -/
#assert (test_early_return_in_loop_break == ok ())

/-- [loop_control_flow::test_return_from_nested_loop_hit]:
    Source: 'tests/src/loop-control-flow.rs', lines 93:0-95:1 -/
def test_return_from_nested_loop_hit : Result Unit := do
  let i ← return_from_nested_loop
  massert (i = 1#u32)

/- Unit test for [loop_control_flow::test_return_from_nested_loop_hit] -/
#assert (test_return_from_nested_loop_hit == ok ())

/-- [loop_control_flow::test_return_value_from_loop_with_break_hit]:
    Source: 'tests/src/loop-control-flow.rs', lines 98:0-100:1 -/
def test_return_value_from_loop_with_break_hit : Result Unit := do
  let i ← return_value_from_loop_with_break 3#u32
  massert (i = 10#u32)

/- Unit test for [loop_control_flow::test_return_value_from_loop_with_break_hit] -/
#assert (test_return_value_from_loop_with_break_hit == ok ())

/-- [loop_control_flow::test_return_value_from_loop_with_break_fallthrough]:
    Source: 'tests/src/loop-control-flow.rs', lines 103:0-105:1 -/
def test_return_value_from_loop_with_break_fallthrough : Result Unit := do
  let i ← return_value_from_loop_with_break 8#u32
  massert (i = 25#u32)

/- Unit test for [loop_control_flow::test_return_value_from_loop_with_break_fallthrough] -/
#assert (test_return_value_from_loop_with_break_fallthrough == ok ())

/-- [loop_control_flow::test_continue_to_outer_loop]:
    Source: 'tests/src/loop-control-flow.rs', lines 108:0-110:1 -/
def test_continue_to_outer_loop : Result Unit := do
  let i ← continue_to_outer_loop
  massert (i = 60#u32)

/- Unit test for [loop_control_flow::test_continue_to_outer_loop] -/
#assert (test_continue_to_outer_loop == ok ())

/-- [loop_control_flow::test_break_to_outer_loop]:
    Source: 'tests/src/loop-control-flow.rs', lines 113:0-115:1 -/
def test_break_to_outer_loop : Result Unit := do
  let i ← break_to_outer_loop
  massert (i = 9#u32)

/- Unit test for [loop_control_flow::test_break_to_outer_loop] -/
#assert (test_break_to_outer_loop == ok ())

end loop_control_flow
