-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loop_nonlocal_exit_shared_tail]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace loop_nonlocal_exit_shared_tail

/-- [loop_nonlocal_exit_shared_tail::check_flag]: loop body 0:
    Source: 'tests/src/loop_nonlocal_exit_shared_tail.rs', lines 27:12-35:1
    Visibility: public -/
@[rust_loop_body]
def check_flag_loop.body
  (byte : Std.U8) (iter : core.slice.iter.Iter Std.U8) :
  Result (ControlFlow (core.slice.iter.Iter Std.U8) (core.result.Result Unit
    Std.U32))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (core.result.Result.Ok ()))
  | some x =>
    if x = byte
    then ok (done (core.result.Result.Err 1#u32))
    else ok (cont iter1)

/-- [loop_nonlocal_exit_shared_tail::check_flag]: loop 0:
    Source: 'tests/src/loop_nonlocal_exit_shared_tail.rs', lines 27:12-35:1
    Visibility: public -/
@[rust_loop]
def check_flag_loop
  (iter : core.slice.iter.Iter Std.U8) (byte : Std.U8) :
  Result (core.result.Result Unit Std.U32)
  := do
  loop
    (fun iter1 => check_flag_loop.body byte iter1)
    iter

/-- [loop_nonlocal_exit_shared_tail::check_flag]:
    Source: 'tests/src/loop_nonlocal_exit_shared_tail.rs', lines 23:0-35:1
    Visibility: public -/
def check_flag
  (flag : Bool) (xs : Slice Std.U8) (byte : Std.U8) :
  Result (core.result.Result Unit Std.U32)
  := do
  if flag
  then ok (core.result.Result.Ok ())
  else let iter ← core.slice.Slice.iter xs
       check_flag_loop iter byte

/-- [loop_nonlocal_exit_shared_tail::Shape]
    Source: 'tests/src/loop_nonlocal_exit_shared_tail.rs', lines 37:0-42:1
    Visibility: public -/
@[discriminant isize]
inductive Shape where
| Empty : Shape
| One : Std.U8 → Shape
| Many : alloc.vec.Vec Std.U8 → Shape
| Pair : Std.U8 → Std.U8 → Shape

/-- [loop_nonlocal_exit_shared_tail::check_shape]: loop body 0:
    Source: 'tests/src/loop_nonlocal_exit_shared_tail.rs', lines 56:12-69:1
    Visibility: public -/
@[rust_loop_body]
def check_shape_loop.body
  (byte : Std.U8) (iter : core.slice.iter.Iter Std.U8) :
  Result (ControlFlow (core.slice.iter.Iter Std.U8) (core.result.Result Unit
    Std.U32))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (core.result.Result.Ok ()))
  | some x =>
    if x = byte
    then ok (done (core.result.Result.Err 2#u32))
    else ok (cont iter1)

/-- [loop_nonlocal_exit_shared_tail::check_shape]: loop 0:
    Source: 'tests/src/loop_nonlocal_exit_shared_tail.rs', lines 56:12-69:1
    Visibility: public -/
@[rust_loop]
def check_shape_loop
  (iter : core.slice.iter.Iter Std.U8) (byte : Std.U8) :
  Result (core.result.Result Unit Std.U32)
  := do
  loop
    (fun iter1 => check_shape_loop.body byte iter1)
    iter

/-- [loop_nonlocal_exit_shared_tail::check_shape]:
    Source: 'tests/src/loop_nonlocal_exit_shared_tail.rs', lines 47:0-69:1
    Visibility: public -/
def check_shape
  (s : Shape) (byte : Std.U8) : Result (core.result.Result Unit Std.U32) := do
  match s with
  | Shape.Empty => ok (core.result.Result.Ok ())
  | Shape.One b =>
    if b = byte
    then ok (core.result.Result.Err 1#u32)
    else ok (core.result.Result.Ok ())
  | Shape.Many xs =>
    let s1 := alloc.vec.Vec.deref xs
    let iter ← core.slice.Slice.iter s1
    check_shape_loop iter byte
  | Shape.Pair a b =>
    if a = byte
    then ok (core.result.Result.Err 3#u32)
    else
      if b = byte
      then ok (core.result.Result.Err 3#u32)
      else ok (core.result.Result.Ok ())

end loop_nonlocal_exit_shared_tail
