-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loops_continue_outer]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace loops_continue_outer

/-- [loops_continue_outer::labelled_continue]: loop body 1:
    Source: 'tests/src/loops-continue-outer.rs', lines 1:0-30:5
    Visibility: public -/
@[rust_loop_body]
def labelled_continue_loop0_loop0.body
  (n : Std.U32) (i : Std.U32) (total : Std.U32) (j : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) (Std.U32 × Std.U32 × Bool))
  := do
  if j < n
  then
    if j = 3#u32
    then let i1 ← i + 1#u32
         ok (done (total, i1, true))
    else
      let total1 ← total + 1#u32
      let j1 ← j + 1#u32
      ok (cont (total1, j1))
  else ok (done (total, i, false))

/-- [loops_continue_outer::labelled_continue]: loop 1:
    Source: 'tests/src/loops-continue-outer.rs', lines 1:0-30:5
    Visibility: public -/
@[rust_loop]
def labelled_continue_loop0_loop0
  (n : Std.U32) (total : Std.U32) (i : Std.U32) (j : Std.U32) :
  Result (Std.U32 × Std.U32 × Bool)
  := do
  loop
    (fun (total1, j1) => labelled_continue_loop0_loop0.body n i total1 j1)
    (total, j)

/-- [loops_continue_outer::labelled_continue]: loop body 0:
    Source: 'tests/src/loops-continue-outer.rs', lines 1:0-30:5
    Visibility: public -/
@[rust_loop_body]
def labelled_continue_loop0.body
  (m : Std.U32) (n : Std.U32) (total : Std.U32) (i : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) Std.U32)
  := do
  if i < m
  then
    let (total1, i1, aeneas_loop_exit) ←
      labelled_continue_loop0_loop0 n total i 0#u32
    if aeneas_loop_exit
    then ok (cont (total1, i1))
    else let i2 ← i1 + 1#u32
         ok (cont (total1, i2))
  else ok (done total)

/-- [loops_continue_outer::labelled_continue]: loop 0:
    Source: 'tests/src/loops-continue-outer.rs', lines 1:0-30:5
    Visibility: public -/
@[rust_loop]
def labelled_continue_loop0
  (m : Std.U32) (n : Std.U32) (total : Std.U32) (i : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (total1, i1) => labelled_continue_loop0.body m n total1 i1)
    (total, i)

/-- [loops_continue_outer::labelled_continue]:
    Source: 'tests/src/loops-continue-outer.rs', lines 16:0-32:1
    Visibility: public -/
@[reducible]
def labelled_continue (m : Std.U32) (n : Std.U32) : Result Std.U32 := do
  labelled_continue_loop0 m n 0#u32 0#u32

end loops_continue_outer
