-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loop_break_dead_borrow]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace loop_break_dead_borrow

/-- [loop_break_dead_borrow::sum_until]: loop body 0:
    Source: 'tests/src/loop_break_dead_borrow.rs', lines 1:0-30:5
    Visibility: public -/
@[rust_loop_body]
def sum_until_loop.body
  {I : Type} (coreitertraitsiteratorIteratorISharedU32Inst :
  core.iter.traits.iterator.Iterator I Std.U32) (iter : I) (acc : Std.U32) :
  Result (ControlFlow (I × Std.U32) Std.U32)
  := do
  let (o, iter1) ← coreitertraitsiteratorIteratorISharedU32Inst.next iter
  match o with
  | none => ok (done acc)
  | some x =>
    if acc > 100#u32
    then ok (done acc)
    else
      let acc1 ← lift (core.num.U32.wrapping_add acc x)
      ok (cont (iter1, acc1))

/-- [loop_break_dead_borrow::sum_until]: loop 0:
    Source: 'tests/src/loop_break_dead_borrow.rs', lines 1:0-30:5
    Visibility: public -/
@[rust_loop]
def sum_until_loop
  {I : Type} (coreitertraitsiteratorIteratorISharedU32Inst :
  core.iter.traits.iterator.Iterator I Std.U32) (iter : I) (acc : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, acc1) => sum_until_loop.body
      coreitertraitsiteratorIteratorISharedU32Inst iter1 acc1)
    (iter, acc)

/-- [loop_break_dead_borrow::sum_until]:
    Source: 'tests/src/loop_break_dead_borrow.rs', lines 23:0-32:1
    Visibility: public -/
@[reducible]
def sum_until
  {I : Type} (coreitertraitsiteratorIteratorISharedAU32Inst :
  core.iter.traits.iterator.Iterator I Std.U32) (it : I) :
  Result Std.U32
  := do
  sum_until_loop coreitertraitsiteratorIteratorISharedAU32Inst it 0#u32

end loop_break_dead_borrow
