-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loop_ended_shared_loan_borrows]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace loop_ended_shared_loan_borrows

/-- [loop_ended_shared_loan_borrows::Kind]
    Source: 'tests/src/loop_ended_shared_loan_borrows.rs', lines 21:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive Kind where
| Leaf : Std.U8 → Kind
| Many : alloc.vec.Vec Std.U8 → Kind

/-- [loop_ended_shared_loan_borrows::Wrap]
    Source: 'tests/src/loop_ended_shared_loan_borrows.rs', lines 26:0-29:1
    Visibility: public -/
structure Wrap where
  kind : Kind
  tag : Std.U32

/-- [loop_ended_shared_loan_borrows::{loop_ended_shared_loan_borrows::Wrap}::wkind]:
    Source: 'tests/src/loop_ended_shared_loan_borrows.rs', lines 32:4-34:5
    Visibility: public -/
def Wrap.wkind (self : Wrap) : Result Kind := do
  ok self.kind

/-- [loop_ended_shared_loan_borrows::scan]: loop body 0:
    Source: 'tests/src/loop_ended_shared_loan_borrows.rs', lines 47:12-55:1
    Visibility: public -/
@[rust_loop_body]
def scan_loop.body
  (byte : Std.U8) (iter : core.slice.iter.Iter Std.U8) :
  Result (ControlFlow (core.slice.iter.Iter Std.U8) (core.result.Result Unit
    Std.U32))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (core.result.Result.Ok ()))
  | some x =>
    if x = byte
    then ok (done (core.result.Result.Err 2#u32))
    else ok (cont iter1)

/-- [loop_ended_shared_loan_borrows::scan]: loop 0:
    Source: 'tests/src/loop_ended_shared_loan_borrows.rs', lines 47:12-55:1
    Visibility: public -/
@[rust_loop]
def scan_loop
  (iter : core.slice.iter.Iter Std.U8) (byte : Std.U8) :
  Result (core.result.Result Unit Std.U32)
  := do
  loop
    (fun iter1 => scan_loop.body byte iter1)
    iter

/-- [loop_ended_shared_loan_borrows::scan]:
    Source: 'tests/src/loop_ended_shared_loan_borrows.rs', lines 39:0-55:1
    Visibility: public -/
def scan
  (w : Wrap) (byte : Std.U8) : Result (core.result.Result Unit Std.U32) := do
  let k ← Wrap.wkind w
  match k with
  | Kind.Leaf b =>
    if b = byte
    then ok (core.result.Result.Err 1#u32)
    else ok (core.result.Result.Ok ())
  | Kind.Many xs =>
    let s := alloc.vec.Vec.deref xs
    let iter ← core.slice.Slice.iter s
    scan_loop iter byte

end loop_ended_shared_loan_borrows
