-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loops_flag_threaded]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace loops_flag_threaded

/-- [loops_flag_threaded::return_from_nested_loop]: loop body 1:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-26:9
    Visibility: public -/
@[rust_loop_body]
def return_from_nested_loop_loop0_loop0.body
  (n : Std.U32) (ret : Option Std.U32) (i : Std.U32) (j : Std.U32) :
  Result (ControlFlow Std.U32 (Option Std.U32))
  := do
  if j < n
  then
    let i1 ← i + j
    if i1 > 10#u32
    then ok (done (some i1))
    else let j1 ← j + 1#u32
         ok (cont j1)
  else ok (done ret)

/-- [loops_flag_threaded::return_from_nested_loop]: loop 1:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-26:9
    Visibility: public -/
@[rust_loop]
def return_from_nested_loop_loop0_loop0
  (n : Std.U32) (ret : Option Std.U32) (i : Std.U32) (j : Std.U32) :
  Result (Option Std.U32)
  := do
  loop
    (fun j1 => return_from_nested_loop_loop0_loop0.body n ret i j1)
    j

/-- [loops_flag_threaded::return_from_nested_loop]: loop body 0:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-31:5
    Visibility: public -/
@[rust_loop_body]
def return_from_nested_loop_loop0.body
  (m : Std.U32) (n : Std.U32) (ret : Option Std.U32) (i : Std.U32) :
  Result (ControlFlow ((Option Std.U32) × Std.U32) (Option Std.U32))
  := do
  if i < m
  then
    let ret1 ← return_from_nested_loop_loop0_loop0 n ret i 0#u32
    let b := core.option.Option.is_some ret1
    if b
    then ok (done ret1)
    else let i1 ← i + 1#u32
         ok (cont (ret1, i1))
  else ok (done ret)

/-- [loops_flag_threaded::return_from_nested_loop]: loop 0:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-31:5
    Visibility: public -/
@[rust_loop]
def return_from_nested_loop_loop0
  (m : Std.U32) (n : Std.U32) (ret : Option Std.U32) (i : Std.U32) :
  Result (Option Std.U32)
  := do
  loop
    (fun (ret1, i1) => return_from_nested_loop_loop0.body m n ret1 i1)
    (ret, i)

/-- [loops_flag_threaded::return_from_nested_loop]:
    Source: 'tests/src/loops-flag-threaded.rs', lines 15:0-36:1
    Visibility: public -/
def return_from_nested_loop (m : Std.U32) (n : Std.U32) : Result Std.U32 := do
  let ret ← return_from_nested_loop_loop0 m n none 0#u32
  match ret with
  | none => ok 0#u32
  | some r => ok r

/-- [loops_flag_threaded::return_from_loop_in_branch]: loop body 0:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-51:9
    Visibility: public -/
@[rust_loop_body]
def return_from_loop_in_branch_loop.body
  (n : Std.U32) (total : Std.U32) (i : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) (Std.U32 × (Option Std.U32)))
  := do
  if i < n
  then
    if i = 7#u32
    then ok (done (total, some 99#u32))
    else let total1 ← total + i
         let i1 ← i + 1#u32
         ok (cont (total1, i1))
  else ok (done (total, none))

/-- [loops_flag_threaded::return_from_loop_in_branch]: loop 0:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-51:9
    Visibility: public -/
@[rust_loop]
def return_from_loop_in_branch_loop
  (n : Std.U32) (total : Std.U32) (i : Std.U32) :
  Result (Std.U32 × (Option Std.U32))
  := do
  loop
    (fun (total1, i1) => return_from_loop_in_branch_loop.body n total1 i1)
    (total, i)

/-- [loops_flag_threaded::return_from_loop_in_branch]:
    Source: 'tests/src/loops-flag-threaded.rs', lines 39:0-57:1
    Visibility: public -/
def return_from_loop_in_branch
  (n : Std.U32) (sel : Bool) : Result Std.U32 := do
  if sel
  then
    let (total, ret) ← return_from_loop_in_branch_loop n 0#u32 0#u32
    match ret with
    | none => ok total
    | some r => ok r
  else ok 0#u32

/-- [loops_flag_threaded::labelled_break]: loop body 1:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-74:9
    Visibility: public -/
@[rust_loop_body]
def labelled_break_loop0_loop0.body
  (n : Std.U32) (i : Std.U32) (total : Std.U32) (j : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) (Std.U32 × Bool))
  := do
  if j < n
  then
    let i1 ← i * j
    if i1 > 50#u32
    then ok (done (total, true))
    else
      let total1 ← total + 1#u32
      let j1 ← j + 1#u32
      ok (cont (total1, j1))
  else ok (done (total, false))

/-- [loops_flag_threaded::labelled_break]: loop 1:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-74:9
    Visibility: public -/
@[rust_loop]
def labelled_break_loop0_loop0
  (n : Std.U32) (total : Std.U32) (i : Std.U32) (j : Std.U32) :
  Result (Std.U32 × Bool)
  := do
  loop
    (fun (total1, j1) => labelled_break_loop0_loop0.body n i total1 j1)
    (total, j)

/-- [loops_flag_threaded::labelled_break]: loop body 0:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-79:5
    Visibility: public -/
@[rust_loop_body]
def labelled_break_loop0.body
  (m : Std.U32) (n : Std.U32) (total : Std.U32) (i : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) Std.U32)
  := do
  if i < m
  then
    let (total1, exit) ← labelled_break_loop0_loop0 n total i 0#u32
    if exit
    then ok (done total1)
    else let i1 ← i + 1#u32
         ok (cont (total1, i1))
  else ok (done total)

/-- [loops_flag_threaded::labelled_break]: loop 0:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-79:5
    Visibility: public -/
@[rust_loop]
def labelled_break_loop0
  (m : Std.U32) (n : Std.U32) (total : Std.U32) (i : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (total1, i1) => labelled_break_loop0.body m n total1 i1)
    (total, i)

/-- [loops_flag_threaded::labelled_break]:
    Source: 'tests/src/loops-flag-threaded.rs', lines 61:0-81:1
    Visibility: public -/
@[reducible]
def labelled_break (m : Std.U32) (n : Std.U32) : Result Std.U32 := do
  labelled_break_loop0 m n 0#u32 0#u32

/-- [loops_flag_threaded::labelled_continue]: loop body 1:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-99:9
    Visibility: public -/
@[rust_loop_body]
def labelled_continue_loop0_loop0.body
  (n : Std.U32) (i : Std.U32) (total : Std.U32) (j : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) (Std.U32 × Std.U32 × Bool))
  := do
  if j < n
  then
    if j = 3#u32
    then let i1 ← i + 1#u32
         ok (done (total, i1, true))
    else
      let total1 ← total + 1#u32
      let j1 ← j + 1#u32
      ok (cont (total1, j1))
  else ok (done (total, i, false))

/-- [loops_flag_threaded::labelled_continue]: loop 1:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-99:9
    Visibility: public -/
@[rust_loop]
def labelled_continue_loop0_loop0
  (n : Std.U32) (total : Std.U32) (i : Std.U32) (j : Std.U32) :
  Result (Std.U32 × Std.U32 × Bool)
  := do
  loop
    (fun (total1, j1) => labelled_continue_loop0_loop0.body n i total1 j1)
    (total, j)

/-- [loops_flag_threaded::labelled_continue]: loop body 0:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-104:5
    Visibility: public -/
@[rust_loop_body]
def labelled_continue_loop0.body
  (m : Std.U32) (n : Std.U32) (total : Std.U32) (i : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) Std.U32)
  := do
  if i < m
  then
    let (total1, i1, skip) ← labelled_continue_loop0_loop0 n total i 0#u32
    if skip
    then ok (cont (total1, i1))
    else let i2 ← i1 + 1#u32
         ok (cont (total1, i2))
  else ok (done total)

/-- [loops_flag_threaded::labelled_continue]: loop 0:
    Source: 'tests/src/loops-flag-threaded.rs', lines 1:0-104:5
    Visibility: public -/
@[rust_loop]
def labelled_continue_loop0
  (m : Std.U32) (n : Std.U32) (total : Std.U32) (i : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (total1, i1) => labelled_continue_loop0.body m n total1 i1)
    (total, i)

/-- [loops_flag_threaded::labelled_continue]:
    Source: 'tests/src/loops-flag-threaded.rs', lines 85:0-106:1
    Visibility: public -/
@[reducible]
def labelled_continue (m : Std.U32) (n : Std.U32) : Result Std.U32 := do
  labelled_continue_loop0 m n 0#u32 0#u32

end loops_flag_threaded
