-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mixed_group_recursion]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace mixed_group_recursion

/-- [mixed_group_recursion::Tree]
    Source: 'tests/src/mixed_group_recursion.rs', lines 43:0-46:1
    Visibility: public -/
@[discriminant isize]
inductive Tree where
| Leaf : Std.U32 → Tree
| Node : Tree → Tree → Tree

/-- [mixed_group_recursion::sum_tree::closure]
    Source: 'tests/src/mixed_group_recursion.rs', lines 54:22-54:43 -/
@[reducible]
def sum_tree.closure := Unit

mutual

/-- [mixed_group_recursion::sum_tree]:
    Source: 'tests/src/mixed_group_recursion.rs', lines 50:0-58:1
    Visibility: public -/
def sum_tree (t : Tree) : Result Std.U32 := do
  match t with
  | Tree.Leaf n => ok n
  | Tree.Node left right =>
    let i ← sum_tree.closure.Insts.CoreOpsFunctionFnTupleTreeU32.call () left
    let i1 ←
      sum_tree.closure.Insts.CoreOpsFunctionFnTupleTreeU32.call () right
    i + i1
partial_fixpoint

/-- [mixed_group_recursion::sum_tree::{impl core::ops::function::Fn<(mixed_group_recursion::Tree,), u32> for mixed_group_recursion::sum_tree::closure}::call]:
    Source: 'tests/src/mixed_group_recursion.rs', lines 54:22-54:43 -/
def sum_tree.closure.Insts.CoreOpsFunctionFnTupleTreeU32.call
  (c : sum_tree.closure) (tupled_args : Tree) : Result Std.U32 := do
  sum_tree tupled_args
partial_fixpoint

end

/-- [mixed_group_recursion::sum_tree::{impl core::ops::function::FnMut<(mixed_group_recursion::Tree,), u32> for mixed_group_recursion::sum_tree::closure}::call_mut]:
    Source: 'tests/src/mixed_group_recursion.rs', lines 54:22-54:43 -/
def sum_tree.closure.Insts.CoreOpsFunctionFnMutTupleTreeU32.call_mut
  (state : sum_tree.closure) (args : Tree) :
  Result (Std.U32 × sum_tree.closure)
  := do
  let i ←
    sum_tree.closure.Insts.CoreOpsFunctionFnTupleTreeU32.call state args
  ok (i, state)

/-- [mixed_group_recursion::sum_tree::{impl core::ops::function::FnOnce<(mixed_group_recursion::Tree,), u32> for mixed_group_recursion::sum_tree::closure}::call_once]:
    Source: 'tests/src/mixed_group_recursion.rs', lines 54:22-54:43 -/
def sum_tree.closure.Insts.CoreOpsFunctionFnOnceTupleTreeU32.call_once
  (c : sum_tree.closure) (t : Tree) : Result Std.U32 := do
  let (i, _) ←
    sum_tree.closure.Insts.CoreOpsFunctionFnMutTupleTreeU32.call_mut c t
  ok i

/-- Trait implementation: [mixed_group_recursion::sum_tree::{impl core::ops::function::FnOnce<(mixed_group_recursion::Tree,), u32> for mixed_group_recursion::sum_tree::closure}]
    Source: 'tests/src/mixed_group_recursion.rs', lines 54:22-54:43 -/
@[reducible]
def sum_tree.closure.Insts.CoreOpsFunctionFnOnceTupleTreeU32 :
  core.ops.function.FnOnce sum_tree.closure Tree Std.U32 := {
  call_once :=
    sum_tree.closure.Insts.CoreOpsFunctionFnOnceTupleTreeU32.call_once
}

/-- Trait implementation: [mixed_group_recursion::sum_tree::{impl core::ops::function::FnMut<(mixed_group_recursion::Tree,), u32> for mixed_group_recursion::sum_tree::closure}]
    Source: 'tests/src/mixed_group_recursion.rs', lines 54:22-54:43 -/
@[reducible]
def sum_tree.closure.Insts.CoreOpsFunctionFnMutTupleTreeU32 :
  core.ops.function.FnMut sum_tree.closure Tree Std.U32 := {
  FnOnceInst := sum_tree.closure.Insts.CoreOpsFunctionFnOnceTupleTreeU32
  call_mut := sum_tree.closure.Insts.CoreOpsFunctionFnMutTupleTreeU32.call_mut
}

/-- Trait implementation: [mixed_group_recursion::sum_tree::{impl core::ops::function::Fn<(mixed_group_recursion::Tree,), u32> for mixed_group_recursion::sum_tree::closure}]
    Source: 'tests/src/mixed_group_recursion.rs', lines 54:22-54:43 -/
@[reducible]
def sum_tree.closure.Insts.CoreOpsFunctionFnTupleTreeU32 : core.ops.function.Fn
  sum_tree.closure Tree Std.U32 := {
  FnMutInst := sum_tree.closure.Insts.CoreOpsFunctionFnMutTupleTreeU32
  call := sum_tree.closure.Insts.CoreOpsFunctionFnTupleTreeU32.call
}

/-- [mixed_group_recursion::unrelated_add]:
    Source: 'tests/src/mixed_group_recursion.rs', lines 64:0-66:1
    Visibility: public -/
def unrelated_add (a : Std.U32) (b : Std.U32) : Result Std.U32 := do
  a + b

end mixed_group_recursion
