-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [promoted_statics]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace promoted_statics

/-- [core::slice::raw::from_ref]:
    Source: '/rustc/library/core/src/slice/raw.rs', lines 203:0-203:39
    Name pattern: [core::slice::raw::from_ref]
    Visibility: public -/
@[rust_fun "core::slice::raw::from_ref"]
axiom core.slice.raw.from_ref {T : Type} : T → Result (Slice T)

/-- [promoted_statics::just_promoted]:
    Source: 'tests/src/promoted_statics.rs', lines 11:0-13:1
    Visibility: public -/
def just_promoted : Result (Slice Std.U8) := do
  ok (Array.to_slice (Array.make 2#usize [ 13#u8, 10#u8 ]))

/-- [promoted_statics::promoted_str]:
    Source: 'tests/src/promoted_statics.rs', lines 16:0-18:1
    Visibility: public -/
def promoted_str : Result Str := do
  ok (toStr "description() is deprecated; use Display")

/-- [promoted_statics::LineTerminator]
    Source: 'tests/src/promoted_statics.rs', lines 20:0-23:1
    Visibility: public -/
@[discriminant isize]
inductive LineTerminator where
| Byte : Std.U8 → LineTerminator
| CRLF : LineTerminator

/-- [promoted_statics::{promoted_statics::LineTerminator}::as_bytes]:
    Source: 'tests/src/promoted_statics.rs', lines 28:4-33:5
    Visibility: public -/
def LineTerminator.as_bytes
  (self : LineTerminator) : Result (Slice Std.U8) := do
  match self with
  | LineTerminator.Byte byte => core.slice.raw.from_ref byte
  | LineTerminator.CRLF =>
    ok (Array.to_slice (Array.make 2#usize [ 13#u8, 10#u8 ]))

/-- [promoted_statics::only_from_ref]:
    Source: 'tests/src/promoted_statics.rs', lines 37:0-39:1
    Visibility: public -/
def only_from_ref (byte : Std.U8) : Result (Slice Std.U8) := do
  core.slice.raw.from_ref byte

end promoted_statics
