-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait_method_assoc_type_constraint]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace trait_method_assoc_type_constraint

/-- Trait declaration: [trait_method_assoc_type_constraint::MyIter]
    Source: 'tests/src/trait_method_assoc_type_constraint.rs', lines 17:0-32:1
    Visibility: public -/
structure MyIter (Self : Type) (Self_Item : Type) where
  next : Self → Result ((Option Self_Item) × Self)
  count_copied : forall {T : Type} {Clause0_Item : Type} (MyIterInst : MyIter
    Self Clause0_Item) (coremarkerCopyInst : core.marker.Copy T), Self →
    Result Std.Usize

/-- [trait_method_assoc_type_constraint::MyIter::count_copied]: loop body 0:
    Source: 'tests/src/trait_method_assoc_type_constraint.rs', lines 27:8-29:9
    Visibility: public -/
@[rust_loop_body, trait_default]
def MyIter.count_copied.default_loop.body
  {Self : Type} {T : Type} (MyIterSelfSharedTInst : MyIter Self T)
  (self : Self) (n : Std.Usize) :
  Result (ControlFlow (Self × Std.Usize) Std.Usize)
  := do
  let (o, self1) ← MyIterSelfSharedTInst.next self
  match o with
  | none => ok (done n)
  | some _ => let n1 ← n + 1#usize
              ok (cont (self1, n1))

/-- [trait_method_assoc_type_constraint::MyIter::count_copied]: loop 0:
    Source: 'tests/src/trait_method_assoc_type_constraint.rs', lines 27:8-29:9
    Visibility: public -/
@[rust_loop, trait_default]
def MyIter.count_copied.default_loop
  {Self : Type} {T : Type} (MyIterSelfSharedTInst : MyIter Self T)
  (self : Self) (n : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (self1, n1) => MyIter.count_copied.default_loop.body
      MyIterSelfSharedTInst self1 n1)
    (self, n)

/-- [trait_method_assoc_type_constraint::MyIter::count_copied]:
    Source: 'tests/src/trait_method_assoc_type_constraint.rs', lines 21:4-31:5
    Visibility: public -/
@[reducible, trait_default]
def MyIter.count_copied.default
  {Self : Type} {T : Type} {Clause1_Item : Type} (MyIterSelfSharedATInst :
  MyIter Self T) (MyIterInst : MyIter Self Clause1_Item) (coremarkerCopyInst :
  core.marker.Copy T) (self : Self) :
  Result Std.Usize
  := do
  MyIter.count_copied.default_loop MyIterSelfSharedATInst self 0#usize

end trait_method_assoc_type_constraint
