-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [vec_recursive_nesting]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace vec_recursive_nesting

/-- [vec_recursive_nesting::VecTree]
    Source: 'tests/src/vec_recursive_nesting.rs', lines 20:0-23:1
    Visibility: public -/
@[discriminant isize]
inductive VecTree where
| Leaf : Std.U32 → VecTree
| Node : _root_.List VecTree → VecTree

/-- [vec_recursive_nesting::vec_tree_is_leaf]:
    Source: 'tests/src/vec_recursive_nesting.rs', lines 28:0-33:1
    Visibility: public -/
def vec_tree_is_leaf (t : VecTree) : Result Bool := do
  match t with
  | VecTree.Leaf _ => ok true
  | VecTree.Node _ => ok false

end vec_recursive_nesting
