-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [vec_recursive_nesting]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section
/- Helper emitted by Aeneas for recursive `Vec` fields that were rewritten
   to `List` (a nested-recursive inductive cannot store `Vec`'s
   `l.length <= Usize.max` bound internally). This monadic coercion
   re-establishes that bound at the field's consumption sites, pushing the
   obligation to the proof layer. It is generated output, NOT part of the
   Aeneas Lean standard library. -/
def Aeneas.VecListNesting.vecOfList {T : Type} (l : List T) :
    Result (alloc.vec.Vec T) :=
  if h : l.length ≤ Usize.max then .ok ⟨l, h⟩ else .fail .panic

namespace vec_recursive_nesting

/-- [alloc::vec::{impl core::iter::traits::collect::IntoIterator<&'a T, core::slice::iter::Iter<'a, T>> for &'a alloc::vec::Vec<T>}::into_iter]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3981:4-3981:40
    Name pattern: [alloc::vec::{core::iter::traits::collect::IntoIterator<&'a alloc::vec::Vec<@T>, &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::iter::traits::collect::IntoIterator<&'a alloc::vec::Vec<@T>, &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter"]
axiom SharedAVec.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (core.slice.iter.Iter T)

/-- [vec_recursive_nesting::VecTree]
    Source: 'tests/src/vec_recursive_nesting.rs', lines 26:0-29:1
    Visibility: public -/
@[discriminant isize]
inductive VecTree where
| Leaf : Std.U32 → VecTree
| Node : _root_.List VecTree → VecTree

/-- [vec_recursive_nesting::vec_tree_is_leaf]:
    Source: 'tests/src/vec_recursive_nesting.rs', lines 33:0-38:1
    Visibility: public -/
def vec_tree_is_leaf (t : VecTree) : Result Bool := do
  match t with
  | VecTree.Leaf _ => ok true
  | VecTree.Node _ => ok false

mutual

/-- [vec_recursive_nesting::VecTreeBranch]
    Source: 'tests/src/vec_recursive_nesting.rs', lines 47:0-49:1
    Visibility: public -/
inductive VecTreeBranch where
| mk : _root_.List VecTreeNode → VecTreeBranch

/-- [vec_recursive_nesting::VecTreeNode]
    Source: 'tests/src/vec_recursive_nesting.rs', lines 51:0-54:1
    Visibility: public -/
@[discriminant isize]
inductive VecTreeNode where
| Leaf : Std.U32 → VecTreeNode
| Node : VecTreeBranch → VecTreeNode

end

def VecTreeBranch.children (x : VecTreeBranch) :=
  match x with | VecTreeBranch.mk x1 => x1

@[simp]
theorem VecTreeBranch.children._simpLemma_ (children : _root_.List VecTreeNode)
  : (VecTreeBranch.mk children).children = children := by rfl

/-- [vec_recursive_nesting::vec_tree_count_children]: loop body 0:
    Source: 'tests/src/vec_recursive_nesting.rs', lines 61:4-63:5
    Visibility: public -/
@[rust_loop_body]
def vec_tree_count_children_loop.body
  (iter : core.slice.iter.Iter VecTreeNode) (n : Std.U64) :
  Result (ControlFlow ((core.slice.iter.Iter VecTreeNode) × Std.U64) Std.U64)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done n)
  | some _ => let n1 ← n + 1#u64
              ok (cont (iter1, n1))

/-- [vec_recursive_nesting::vec_tree_count_children]: loop 0:
    Source: 'tests/src/vec_recursive_nesting.rs', lines 61:4-63:5
    Visibility: public -/
@[rust_loop]
def vec_tree_count_children_loop
  (iter : core.slice.iter.Iter VecTreeNode) (n : Std.U64) :
  Result Std.U64
  := do
  loop
    (fun (iter1, n1) => vec_tree_count_children_loop.body iter1 n1)
    (iter, n)

/-- [vec_recursive_nesting::vec_tree_count_children]:
    Source: 'tests/src/vec_recursive_nesting.rs', lines 59:0-65:1
    Visibility: public -/
def vec_tree_count_children (b : VecTreeBranch) : Result Std.U64 := do
  let iter ←
    do
    let v ← Aeneas.VecListNesting.vecOfList b.children
    SharedAVec.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
      Global v
  vec_tree_count_children_loop iter 0#u64

end vec_recursive_nesting
